# poses.yaml
poses:
  - header:
      frame_id: "odom"
    pose:
      position:
        x: 1.0
        y: 2.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: -1.5
        y: 0.0
        z: 0.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.707
        w: 0.707

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 0.0
        y: -2.0
        z: 1.0
      orientation:
        x: 0.0
        y: 0.707
        z: 0.0
        w: 0.707
