poses:
  - header:
      frame_id: "odom"
    pose:
      position:
        x: 0.0
        y: 0.0
        z: 1.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 8.0
        y: 0.0
        z: 1.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 8.0
        y: 7.0
        z: 1.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 17.0
        y: 7.0
        z: 1.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 17.0
        y: 0.0
        z: 1.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 17.0
        y: 7.0
        z: 1.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 8.0
        y: 7.0
        z: 1.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 8.0
        y: 0.0
        z: 1.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - header:
      frame_id: "odom"
    pose:
      position:
        x: 0.0
        y: 0.0
        z: 1.5
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
